name: Tests
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

env:
  UPSTASH_VECTOR_REST_URL: ${{ secrets.UPSTASH_VECTOR_REST_URL }}
  UPSTASH_VECTOR_REST_TOKEN: ${{ secrets.UPSTASH_VECTOR_REST_TOKEN }}
  UPSTASH_REDIS_REST_URL: ${{secrets.UPSTASH_REDIS_REST_URL}}
  UPSTASH_REDIS_REST_TOKEN: ${{secrets.UPSTASH_REDIS_REST_TOKEN}}
  OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
  QSTASH_TOKEN: ${{secrets.QSTASH_TOKEN}}

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: test

    name: Tests
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Run Lint
        run: bun run fmt

      - name: Run tests
        run: bun run test

      - name: Run Build
        run: bun run build

  cloudflare-workers-local:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Install example
        run: bun add @upstash/rag-chat@../../dist
        working-directory: examples/cloudflare-workers

      - name: Add environment
        run: |
          echo '[vars]' >> wrangler.toml
          echo "UPSTASH_VECTOR_REST_URL = \"$UPSTASH_VECTOR_REST_URL\"" >> ./wrangler.toml
          echo "UPSTASH_VECTOR_REST_TOKEN = \"$UPSTASH_VECTOR_REST_TOKEN\"" >> ./wrangler.toml
          echo "UPSTASH_REDIS_REST_URL = \"$UPSTASH_REDIS_REST_URL\"" >> ./wrangler.toml
          echo "UPSTASH_REDIS_REST_TOKEN = \"$UPSTASH_REDIS_REST_TOKEN\"" >> ./wrangler.toml
          echo "QSTASH_TOKEN = \"$QSTASH_TOKEN\"" >> ./wrangler.toml
        working-directory: examples/cloudflare-workers

      - name: Start example
        run: bun dev &
        working-directory: examples/cloudflare-workers

      - name: Test
        run: bun test ci.test.ts
        working-directory: examples/cloudflare-workers
        env:
          DEPLOYMENT_URL: http://localhost:3000

  nodejs-local:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Install example
        run: bun add @upstash/rag-chat@../../dist
        working-directory: examples/nodejs

      - name: Run example
        run: npm run dev &
        working-directory: examples/nodejs

      - name: Test
        run: bun test ci.test.ts
        working-directory: examples/nodejs
        env:
          DEPLOYMENT_URL: http://localhost:3000

  nextjs-chat-to-website:
    # skip because there is an issue in how the page interacts with local build
    # it's tested in pre-release
    if: false
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Install example
        run: bun add @upstash/rag-chat@../../../dist
        working-directory: examples/nextjs/chat-to-website

      - name: Build example
        run: bun run build
        working-directory: examples/nextjs/chat-to-website

      - name: Run example
        run: npm run start &
        working-directory: examples/nextjs/chat-to-website

      - name: Test
        run: bun test ci.test.ts
        working-directory: examples/nextjs/chat-to-website
        env:
          DEPLOYMENT_URL: http://localhost:3000

  nextjs-server-actions:
    if: false # skip because we can't reliably call server action
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Install example
        run: bun add @upstash/rag-chat@../../../dist
        working-directory: examples/nextjs/server-actions

      - name: Build example
        run: bun run build
        working-directory: examples/nextjs/server-actions

      - name: Run example
        run: npm run start &
        working-directory: examples/nextjs/server-actions

      - name: Test
        run: bun test ci.test.ts
        working-directory: examples/nextjs/server-actions
        env:
          DEPLOYMENT_URL: http://localhost:3000

  nextjs-vercel-ai-sdk:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Install example
        run: bun add @upstash/rag-chat@../../../dist
        working-directory: examples/nextjs/vercel-ai-sdk

      - name: Build example
        run: bun run build
        working-directory: examples/nextjs/vercel-ai-sdk

      - name: Run example
        run: npm run start &
        working-directory: examples/nextjs/vercel-ai-sdk

      - name: Test
        run: bun test ci.test.ts
        working-directory: examples/nextjs/vercel-ai-sdk
        env:
          DEPLOYMENT_URL: http://localhost:3000
